dataset:
  data_path: '$ALFWORLD_DATA/json_2.1.1/train'
  eval_id_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_seen'
  eval_ood_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_unseen'
  num_train_games: -1
  num_eval_games: -1

logic:
  domain: '$ALFWORLD_DATA/logic/alfred.pddl'
  grammar: '$ALFWORLD_DATA/logic/alfred.twl2'

env:
  type: 'AlfredTWEnv'
  domain_randomization: False
  task_types: [1, 2, 3, 4, 5, 6]
  expert_timeout_steps: 150
  expert_type: "handcoded"
  goal_desc_human_anns_prob: 0.0

  hybrid:
    start_eps: 100000
    thor_prob: 0.5
    eval_mode: "tw"

  thor:
    screen_width: 300
    screen_height: 300
    smooth_nav: False
    save_frames_to_disk: False
    save_frames_path: './videos/'

controller:
  type: 'oracle'
  debug: False
  load_receps: True

mask_rcnn:
  pretrained_model_path: '$ALFWORLD_DATA/detectors/mrcnn.pth'

general:
  random_seed: 42
  use_cuda: False
  visdom: False
  task: 'alfred'
  training_method: 'dagger'
  save_path: './training/'
  observation_pool_capacity: 3
  hide_init_receptacles: False

  training:
    batch_size: 10
    max_episode: 50000
    smoothing_eps: 0.1
    optimizer:
      learning_rate: 0.001
      clip_grad_norm: 5

  evaluate:
    run_eval: True
    batch_size: 1
    env:
      type: "AlfredTWEnv"

  checkpoint:
    report_frequency: 1000
    experiment_tag: 'test'
    load_pretrained: False
    load_from_tag: 'not loading anything'

  model:
    encoder_layers: 1
    decoder_layers: 1
    encoder_conv_num: 5
    block_hidden_dim: 64
    n_heads: 1
    dropout: 0.1
    block_dropout: 0.1
    recurrent: True

rl:
  action_space: "admissible"
  max_target_length: 20
  beam_width: 10
  generate_top_k: 3

  training:
    max_nb_steps_per_episode: 50
    learn_start_from_this_episode: 0
    target_net_update_frequency: 500

  replay:
    accumulate_reward_from_final: True
    count_reward_lambda: 0.0
    novel_object_reward_lambda: 0.0
    discount_gamma_game_reward: 0.9
    discount_gamma_count_reward: 0.5
    discount_gamma_novel_object_reward: 0.5
    replay_memory_capacity: 500000
    replay_memory_priority_fraction: 0.5
    update_per_k_game_steps: 5
    replay_batch_size: 64
    multi_step: 3
    replay_sample_history_length: 4
    replay_sample_update_from: 2

  epsilon_greedy:
    noisy_net: False
    epsilon_anneal_episodes: 1000
    epsilon_anneal_from: 0.3
    epsilon_anneal_to: 0.1

dagger:
  action_space: "generation"
  max_target_length: 20
  beam_width: 10
  generate_top_k: 5
  unstick_by_beam_search: False

  training:
    max_nb_steps_per_episode: 50

  fraction_assist:
    fraction_assist_anneal_episodes: 50000
    fraction_assist_anneal_from: 1.0
    fraction_assist_anneal_to: 0.01

  fraction_random:
    fraction_random_anneal_episodes: 0
    fraction_random_anneal_from: 0.0
    fraction_random_anneal_to: 0.0

  replay:
    replay_memory_capacity: 500000
    update_per_k_game_steps: 5
    replay_batch_size: 64
    replay_sample_history_length: 4
    replay_sample_update_from: 2

vision_dagger:
  model_type: "resnet"
  resnet_fc_dim: 64
  maskrcnn_top_k_boxes: 10
  use_exploration_frame_feats: False
  sequence_aggregation_method: "average"
